languageCode = "en"
languageName = "English"
weight = 2
title = "Raphaël Bellec"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  description = "Personal blog of Raphaël Bellec"

[params.author]
  name = "Raphaël Bellec"
  headline = "Personal blog"
